org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin
kotlin.code.style=official

# Android
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
# Versions
kotlin.version=1.9.24
agp.version=8.5.0
compose.compiler.version=1.5.14
hilt.version=2.50
room.version=2.6.1
compose.bom.version=2024.10.00
coroutines.version=1.9.0
camerax.version=1.4.0
mlkit.barcode.version=17.3.0
accompanist.version=0.32.0
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
