org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Kotlin
kotlin.code.style=official

# Android
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Versions
kotlin.version=2.3.20
agp.version=8.13.2
hilt.version=2.58
room.version=2.8.4
compose.bom.version=2024.10.00
coroutines.version=1.9.0
camerax.version=1.4.0
mlkit.barcode.version=17.3.0
accompanist.version=0.32.0
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
